[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "encounter"
version = "4.19.0"
requires-python = ">=3.11"

[tool.setuptools]
package-dir = {"" = "src"}
